export const SHOW_ALERT = "SHOW_ALERT"
export const HIDE_ALERT = "HIDE_ALERT"

export const ADD_NOTE = "ADD_NOTE"
export const DELETE_NOTE = "DELETE_NOTE"
export const FETCH_NOTES = "FETCH_NOTES"
export const SHOW_LOADER = "SHOW_LOADER"
export const TOGGLE_NOTE = "TOGGLE_NOTE"
export const SORT_NOTES = "SORT_NOTES"
export const SET_SEARCH_VAL = "SET_SEARCH_VAL"